# Generated by Django 5.2.1 on 2025-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
